---
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
  - direction: Vertical
    plugin: target/wasm32-wasi/debug/rust-plugin-example.wasm
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar
